<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Colorful.Console" Version="1.2.15" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\I18nExtensions\I18nExtensions.csproj" />
      <ProjectReference Include="..\ModuleLoadSources\ModuleLoadSources.csproj" />
      <ProjectReference Include="..\RestSharp\RestSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Utils\" />
    </ItemGroup>

</Project>
