<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsRoslynComponent>true</IsRoslynComponent>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" GeneratePathProperty="true" />
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md;AnalyzerReleases.Unshipped.md" />
    </ItemGroup>
    <PropertyGroup>
        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);IncludeGeneratorDependencies</GetTargetPathDependsOn>
    </PropertyGroup>
    <Target Name="IncludeGeneratorDependencies">
        <ItemGroup>
            <TargetPathWithTargetPlatformMoniker Include="$(PkgNewtonsoft_Json)/lib/netstandard2.0/Newtonsoft.Json.dll"
                                                IncludeRuntimeDependency="false" />
        </ItemGroup>
    </Target>
</Project>
